### ISSUE TITLE
Schema compatibility validation

### ISSUE THREAD

**Issue by rafaparadela** [higherkindness/compendium#10]
When updating a schema, compendium should be able to check compatibility.

This process would roughly be:

1. Calculate the diff between both
2. Check if the changes are retrocompatible
3. In case of non-retrocompatible changes, don't allow PATCH nor MINOR updates, only MAJOR.

To be able to execute this task, we will need to introduce tree-diffing in Droste.  We can get inspiration from Matryoshka's diff https://github.com/slamdata/matryoshka/blob/master/core/shared/src/main/scala/matryoshka/patterns/Diff.scala

**Comment by diesalbla** [comment]
The comparison/diff algorithm involving 1. and 2. was implemented in the Skeumorph project, in https://github.com/higherkindness/skeuomorph/pull/82.
