### ISSUE TITLE
Compendium Client should be polymorphic in its effect type

### ISSUE THREAD

**Issue by rlmark** [higherkindness/compendium#114]
When working on the Marlow issue for creating a sample app (https://github.com/47deg/marlow/issues/264) I realized that the Compendium Client relies on a specific effect type, Cats-effect IO. It might be nice for this library to allow the caller to supply their own effect type, provided it meets the type class constraint requirements dictated by the underlying integration with Hammock (a `Sync` instance, I believe.) 

In terms of developer ergonomics, the change to users of the client would be fairly minimal. The client is currently instantiated via code that looks like this: 
```
implicit val terp = interp("proto1", IdlName.Scala)
val client = CompendiumClient()
```

And if we were to allow the effect to vary, instantiating the same client might look like: 
```
implicit val terp = interp[Task]("proto1", IdlName.Scala)
val client = CompendiumClient[Task]()
// Or 
implicit val terp = interp[IO]("proto1", IdlName.Scala)
val client = CompendiumClient[IO]()
```

Note that this is a contract level change, so if we have any users of the client currently, we should be aware of the effect on them. 

If this issue is something we'd like sooner, rather than later, I have a local branch on my machine ready for PR, but if we'd rather not change the client for this release (or ever!), I understand that as well! 😃

**Comment by pirita** [comment]
Sure! So far the only client that uses compendium is `sbt-compendium`. I think we found some issues when we were creating the sbt plugin, but I don't remember them right now :( .

I am fine with making polymorphic the client. As soon as we review and merge your PR, I'll update my PR of the `sbt-compendium` with the client changes.

**Comment by rlmark** [comment]
Closed via https://github.com/higherkindness/compendium/pull/117
