### ISSUE TITLE
Create storage layer for handling schemas persistence

### ISSUE THREAD

**Issue by JesusMtnez** [higherkindness/compendium#13]
Provide a first implementation for the `Storage` in `compendium`.
- [x] Create first abstraction for `Storage`, providing:
  - Save _schema_
  - Retrieve schema
- [x] Provide an implementation for:
  - **TBD** (Redis, etcd, consul, counchdb,...)

**Comment by pirita** [comment]
Yes. It is the simplest implementation possible. In the future, we may use a real DB, another storage or support multiple schemas.

**Comment by JesusMtnez** [comment]
Already done!
