### ISSUE TITLE
Validate non avro schema 

### ISSUE THREAD

**Issue by mrtmmr** [higherkindness/compendium#189]
[Current protocol validation](https://github.com/higherkindness/compendium/blob/master/src/main/scala/higherkindness/compendium/core/ProtocolUtils.scala#L31) only handles avro schemas. For each schema supported (expected Avro, Protobuf, Mu, OpenApi but not necessary all at once) it should handle its schema type.

**Comment by JesusMtnez** [comment]
@mrtmmr this one can be close, right?

**Comment by mrtmmr** [comment]
Also, another issue for Mu is needed (besides https://github.com/higherkindness/compendium/issues/30)
