### ISSUE TITLE
In DB storage case, create metaprotocol and protocol tables properly 

### ISSUE THREAD

**Issue by mrtmmr** [higherkindness/compendium#205]
`protocols`  table isn't  created when database storage is chosen.  

Even though, `Migration.dataLocation` is added to the migration creation (https://github.com/higherkindness/compendium/blob/c8da2e8bf74b76fa2211b1c67114d8f054341d53/src/main/scala/higherkindness/compendium/Main.scala#L52), it fails with the  exception:
```
[ioapp-compute-0] INFO org.flywaydb.core.internal.database.DatabaseFactory - Database: jdbc:postgresql://localhost:5432/postgres (PostgreSQL 10.8)
org.flywaydb.core.api.FlywayException: Validate failed: 
Migration checksum mismatch for migration version 1
-> Applied to database : 1312974013
-> Resolved locally    : 1791795912
```

Each table should be created based on its own configuration.

**Comment by JesusMtnez** [comment]
Let's keep  `metadata` and `data` in separate databases. We should provide support for that even using the same Postgres instance. Let handle the connection for `metadata` and `data` databases separately.

**Comment by mrtmmr** [comment]
I created [this PR](https://github.com/higherkindness/compendium/pull/208) in order to make some tests for this issue. So, is it okay for you if I close the PR and delete the branch, @JesusMtnez ?

**Comment by JesusMtnez** [comment]
I'll handle that :wink:
