### ISSUE TITLE
Return better error status code

### ISSUE THREAD

**Issue by pirita** [higherkindness/compendium#28]
We need to improve the status code returned by compendium. For example, if the json is [incorrect](https://github.com/higherkindness/compendium/blob/11d731e2ea10d8e800ff24d87a684c4bada0709c/src/main/scala/higherkindness/compendium/http/RootService.scala#L46) we should return a `Bad request` instead of `Internal server error`.

**Comment by JesusMtnez** [comment]
What happens if the `json` is invalid (not only the protocol) ?

**Comment by Yawolf** [comment]
I would say to use a `422 Unprocessable entity` when the `Json` is not well formed or invalid
