### ISSUE TITLE
Define all the compendium endpoints in OpenAPI

### ISSUE THREAD

**Issue by pirita** [higherkindness/compendium#31]
Define all the compendium endpoints in OpenAPI

**Comment by rlmark** [comment]
Hi @alejandrohdezma! I hope not to have re-invented the wheel here as I realize you may have done a lot of this task before I hopped on to help out with Compendium, but as part of some explorations related to how we want to handle the compendium HTTP client [Discussion here](https://github.com/higherkindness/compendium/issues/118) I ended up writing some openAPI specifications for the service. For ease of tracking progress towards this goal, the branch I was working on is called [openAPI-specification](https://github.com/higherkindness/compendium/tree/openAPI-specification). I believe the specification to be complete in representing the current service endpoints but of course, as time goes on, that may drift and change. Would you like me to create a PR?

**Comment by alejandrohdezma** [comment]
Hey @rlmark no problem at all, I had completely forgot about this issue as I didn't find time to start it in the first place, so feel free to assign it to yourself :) Thanks!
