### ISSUE TITLE
Document compendium for release 0.0.1

### ISSUE THREAD

**Issue by pepegar** [higherkindness/compendium#45]
Once the microsite is set up, we should add the documentation for all the current features that will be included in version 0.0.1

- [x] Welcome page: #201 
- [ ] Getting started
- [ ] Features
- [x] Deployment: #226 
- [x] sbt-compendium: #237 
- [x] OpenAPI documentation #240

**Comment by JesusMtnez** [comment]
Initial structure: https://github.com/higherkindness/compendium/pull/201

**Comment by JesusMtnez** [comment]
Deployment section is included here: https://github.com/higherkindness/compendium/pull/226

**Comment by Yawolf** [comment]
I can take care of the `Features` page(s)

**Comment by mrtmmr** [comment]
I can start the `sbt-compendium` part
