### ISSUE TITLE
Improve server endpoints error handling

### ISSUE THREAD

**Issue by bilki** [higherkindness/compendium#85]
Currently we are handling errors directly inside the compendium server endpoints.

* Add errors with proper encoding (improve current generic `ErrorResponse`)
* Decide how to transform specific Avro, http4s, refined, etc. into those errors
* Inject a handler into root service, to decide which http response and transformation is needed

**Comment by JesusMtnez** [comment]
Related info: https://typelevel.org/blog/2018/11/28/http4s-error-handling-mtl-2.html

I've done a similar approach elsewhere, but I think it would be a great addition since we could expect this API to gain more complexity in the future.

Great idea! :clap:
