### ISSUE TITLE
Support schema versioning

### ISSUE THREAD

**Issue by JesusMtnez** [higherkindness/compendium#92]
As a first attempt to support schema versioning, `compendium` should handle a simple with autoincrement versioning system.

- When a new schema is created, it will have `v1` version.
- Each update to that schema will generate a new version: `v2`, `v3` and so on.

**Comment by juanpedromoreno** [comment]
I'm wondering if it would make sense to use something similar to `SemVer` for versioning data schemas (backward compatibility management).

**Comment by JesusMtnez** [comment]
That is the approach we want to migrate in future releases. But for that, we would require `skeuomorph` to be able to analyze the diff between two versions to decide if want kind of version update is necessary. For the first approach, we are going to keep it more simple until we could offer that kind of versioning.
