### ISSUE TITLE
Generate Protobuf from any other IDL

### ISSUE THREAD

**Issue by Yawolf** [higherkindness/compendium#97]
Related with #12

We need to add the ability to generate a Protobuf schema from these IDL:
- [ ] Avro
- [ ] Openapi
- [ ] Mu

**Comment by bilki** [comment]
I assign this myself to do a bit of sketching, to know if we have all the necessary pieces in place.

**Comment by bilki** [comment]
As of skeuomorph 0.0.11, we are missing all the necessary transformations:

- Avro to Protobuf (see https://github.com/higherkindness/skeuomorph/issues/110, @AlvaroCaste is working on a bidirectional translation)
- Openapi to Protobuf
- Mu to Protobuf

**Comment by JesusMtnez** [comment]
Since schema transformations are out of the scope, I think this one should be closed.
